# テスト実行
on:
  push:
    branches:
      - "main"
  pull_request:

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
    services:
      # RDBMSを使ったテストコード実行のため、MySQLコンテナを起動する
      mysql:
        image: mysql:8
        # MySQLコンテナが使用可能になるまで待機するコマンド
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todo
          MYSQL_USER: todo
          MYSQL_PASSWORD: todo
      # Redis
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actions/checkout@v3
    # mysqldefをインストールし、DBマイグレート
    - run: |
        go install github.com/k0kubun/sqldef/cmd/mysqldef@latest
        mysqldef -u todo -p todo -h 127.0.0.1 -P 3306 todo < ./_tools/mysql/schema.sql
    # go:embedしているファイルがないとテスト失敗するので作成
    - run: |
        mkdir ./auth/cert
        echo -n $SECRET_KEY | base64 --decode > ./auth/cert/secret.pem
        echo -n $PUBLIC_KEY | base64 --decode > ./auth/cert/public.pem
    - run: go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0
